spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datalayer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

storage:
  root-path: ./storage-data